tnt-wand-config-gui:
  size: 18
  name: "&6&lTNT Wand Options"
  1:
    slot: 5
    name: "&b&lSwitch Tool Mode"
    material: ender_pearl:0
    lore:
      - "&7 "
      - "&7&oClick this to change your TNT Wands"
      - "&7&omode. There are craft and bank modes."
      - "&7 "
    switch-mode-when-clicked: true
  2:
    slot: 3
    name: "&a&lDecrease Crafting Cost"
    material: stained_glass_pane:5
    lore:
      - "&7 "
      - "&7&oClick to decrease your TNT Wands"
      - "&7&ocrafting cost per item by 1 tier."
      - "&7 "
    increase-modifier-when-clicked: true
  4:
    slot: 13
    name: "&e&lTNT Wand Information"
    material: book:0
    lore:
      - "&7 "
      - "&7&oTNT wands have special properties,"
      - "&7&owhich means they can be configured to suit"
      - "&7&oyour explosion needs. Click the buttons"
      - "&7&oin this gui to configure your wand."
      - "&7 "
      - "&6&oYou must be holding your TNT Wand."
      - "&7 "
    enchantments:
      - lure:1
