multi-tool-config-gui:
  size: 18
  name: "&6&lMulti Tool Options"
  1:
    slot: 5
    name: "&b&lSwitch Tool Mode"
    material: ender_pearl:0
    lore:
      - "&7 "
      - "&7&oClick this to change your Multi Tools"
      - "&7&omode. There are tray and trench modes."
      - "&7 "
    switch-mode-when-clicked: true
  2:
    slot: 3
    name: "&a&lIncrease Break Radius"
    material: stained_glass_pane:5
    lore:
      - "&7 "
      - "&7&oClick to increase your Multi Tools"
      - "&7&obreak radius by 1 block."
      - "&7 "
    increase-radius-when-clicked: true
  3:
    slot: 2
    name: "&c&lDecrease Break Radius"
    material: stained_glass_pane:14
    lore:
      - "&7 "
      - "&7&oClick to decrease your Multi Tools"
      - "&7&obreak radius by 1 block."
      - "&7 "
    decrease-radius-when-clicked: true
  4:
    slot: 13
    name: "&e&lMulti Tool Information"
    material: book:0
    lore:
      - "&7 "
      - "&7&oMulti Tools have special properties,"
      - "&7&owhich means they can be configured to suit"
      - "&7&oyour trench / tray needs. Click the buttons"
      - "&7&oin this gui to configure your tool."
      - "&7 "
      - "&6&oYou must be holding your Multi Tool."
      - "&7 "
    enchantments:
      - lure:1
