chunk-wand-config-gui:
  size: 18
  name: "&6&lChunk Wand Options"
  1:
    slot: 2
    name: "&c&lDecrease Buster Radius"
    material: red_mushroom:0
    lore:
      - "&7 "
      - "&7&oClick to decrease your Chunk Wand's"
      - "&7&oreach by 1 chunk on each side."
      - "&7 "
    decrease-radius-when-clicked: true
  2:
    slot: 3
    name: "&a&lIncrease Buster Radius"
    material: brown_mushroom:0
    lore:
      - "&7 "
      - "&7&oClick to increase your Chunk Wand's"
      - "&7&oreach by 1 chunk on each side."
      - "&7 "
    increase-radius-when-clicked: true
  3:
    slot: 13
    name: "&e&lChunk Wand Information"
    material: book:0
    lore:
      - "&7 "
      - "&7&oChunk Wands have special properties,"
      - "&7&owhich means they can be configured to suit"
      - "&7&oyour chunk busting needs. Click the buttons"
      - "&7&oin this gui to configure your wand."
      - "&7 "
      - "&6&oYou must be holding your Chunk wand."
      - "&7 "
    enchantments:
      - lure:1
