crops:
  enabled: true
  auto-replant: true
  ripe-data: 7
  multi-drop:
    enabled: true
    min: 1
    max: 3

carrot:
  enabled: true
  auto-replant: true
  ripe-data: 7
  multi-drop:
    enabled: true
    min: 1
    max: 3

potato:
  enabled: true
  auto-replant: true
  ripe-data: 7
  multi-drop:
    enabled: true
    min: 1
    max: 3

pumpkin:
  enabled: true
  auto-replant: false
  ripe-data: 0
  multi-drop:
    enabled: false
    min: 1
    max: 1

melon:
  enabled: true
  auto-replant: false
  ripe-data: 0
  multi-drop:
    enabled: true
    min: 1
    max: 6

cocoa:
  enabled: true
  auto-replant: true
  ripe-data: 8
  multi-drop:
    enabled: true
    min: 1
    max: 3

beetroot:
  enabled: true
  auto-replant: true
  ripe-data: 7
  multi-drop:
    enabled: true
    min: 1
    max: 3

nether_wart:
  enabled: true
  auto-replant: true
  ripe-data: 7
  multi-drop:
    enabled: true
    min: 1
    max: 3

sugar_cane:
  enabled: true
  auto-replant: false
  ripe-data: 0
  multi-drop:
    enabled: false
    min: 1
    max: 1

cactus:
  enabled: true
  auto-replant: false
  ripe-data: 0
  multi-drop:
    enabled: false
    min: 1
    max: 1