harvester-tool-config-gui:
  size: 18
  name: "&6&lHarvester Hoe Options"
  1:
    slot: 5
    name: "&b&lSwitch Tool Mode"
    material: ender_pearl:0
    lore:
      - "&7 "
      - "&7&oClick this to change your Harvester Hoes"
      - "&7&omode. There are sell and harvest modes."
      - "&7 "
    switch-mode-when-clicked: true
  2:
    slot: 3
    name: "&a&lIncrease Price Modifier"
    material: stained_glass_pane:5
    lore:
      - "&7 "
      - "&7&oClick to increase your Harvester Hoes"
      - "&7&oprice modifier by 1 tier."
      - "&7 "
    increase-modifier-when-clicked: true
  4:
    slot: 13
    name: "&e&lHarvester Hoe Information"
    material: book:0
    lore:
      - "&7 "
      - "&7&oHarvester Hoes have special properties,"
      - "&7&owhich means they can be configured to suit"
      - "&7&oyour harvesting needs. Click the buttons"
      - "&7&oin this gui to configure your tool."
      - "&7 "
      - "&6&oYou must be holding your Harvester Hoe."
      - "&7 "
    enchantments:
      - lure:1
